Make script for copying binaries for sudo -E expressions handle cp error.

diff --git a/_sudoe b/_sudoe
--- a/_sudoe
+++ b/_sudoe
@@ -8,16 +8,29 @@ _make_sudo_e() {
 
   if ! _path="$(command -v "$_bin")"; then
     echo "Path for binary $_bin not found. Exiting."
-    exit 1
+    return 1
   fi
 
   _dirname="$(dirname "$_path")"
 
-  local _copied_bin="$_dirname/${_bin}_sudo_e"
+  local _new_bin_name="${_bin}_sudo_e"
+  local _copied_bin="$_dirname/$_new_bin_name"
 
-  sudo cp "$_path" "$_copied_bin"
+  if ! sudo cp "$_path" "$_copied_bin"; then
+    local _local_bin="$HOME/.local/bin"
+    _copied_bin="$_local_bin/$_new_bin_name"
 
-  echo "New bin at $_copied_bin"
+    mkdir -p "$_local_bin"
+    cp "$_path" "$_copied_bin"
+  fi
+
+  if [[ -s "$_copied_bin" ]]; then
+    echo "New bin at $_copied_bin."
+    return 0
+  fi
+
+  echo "Unable to copy binary for \"$_bin\"."
+  return 1
 }
 
 _make_sudo_e "$@"
