run.sh template - raise if env filename set to .env.example

diff --git a/task-file/Taskfile.template b/task-file/Taskfile.template
--- a/task-file/Taskfile.template
+++ b/task-file/Taskfile.template
@@ -65,6 +65,11 @@ function _timestamp {
 
 function _raise_on_no_env_file {
   if [[ -n "$SOME_ENV_EXISTS" ]]; then
+    if [[ "$SOME_ENV_EXISTS" =~ .env.example ]]; then
+      printf "\nERROR: env filename can not be .env.example.\n\n"
+      exit 1
+    fi
+
     return 0
   fi
 
