task template: more helper functions

diff --git a/task-file/Taskfile.template b/task-file/Taskfile.template
--- a/task-file/Taskfile.template
+++ b/task-file/Taskfile.template
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck disable=1090
 
 # -----------------------------------------------------------------------------
 # See also for inspiration:
@@ -24,7 +25,22 @@ function _helper_function {
     env=".env"
   fi
 
+  set -a
+  . $env
+  set +a
+
   splitenvs "$env" --lines
+}
+
+function _timestamp {
+  date +'%s'
+}
+
+function _raise_on_no_env_file {
+  if [[ -z "$1" ]] || [[ ! -e "$1" ]]; then
+    printf "\nenv filename has not been provided or invalid\n\n"
+    exit 1
+  fi
 }
 
 function install {
